// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeAPI.Data.Entities;

public partial class Categories
{
    public int CategoryId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Recipes> Recipe { get; set; } = new List<Recipes>();
}