// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeAPI.Data.Entities;

public partial class MealPlanItems
{
    public int MealPlanItemId { get; set; }

    public int MealPlanId { get; set; }

    public int RecipeId { get; set; }

    public DateTime PlannedDate { get; set; }

    public string MealType { get; set; }

    public int Servings { get; set; }

    public virtual MealPlans MealPlan { get; set; }

    public virtual Recipes Recipe { get; set; }
}