// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeAPI.Data.Entities;

public partial class Recipes
{
    public int RecipeId { get; set; }

    public int? UserId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? PrepTime { get; set; }

    public int? CookTime { get; set; }

    public int? Servings { get; set; }

    public string Instructions { get; set; }

    public string ImageUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<MealPlanItems> MealPlanItems { get; set; } = new List<MealPlanItems>();

    public virtual ICollection<RecipeIngredients> RecipeIngredients { get; set; } = new List<RecipeIngredients>();

    public virtual Users User { get; set; }

    public virtual ICollection<Categories> Category { get; set; } = new List<Categories>();
}