// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeAPI.Data.Entities;

public partial class RecipeIngredients
{
    public int RecipeId { get; set; }

    public int IngredientId { get; set; }

    public int? UnitId { get; set; }

    public decimal Quantity { get; set; }

    public string Notes { get; set; }

    public virtual Ingredients Ingredient { get; set; }

    public virtual Recipes Recipe { get; set; }

    public virtual Units Unit { get; set; }
}