// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeAPI.Data.Entities;

public partial class Units
{
    public int UnitId { get; set; }

    public string Name { get; set; }

    public string Abbreviation { get; set; }

    public string UnitType { get; set; }

    public virtual ICollection<RecipeIngredients> RecipeIngredients { get; set; } = new List<RecipeIngredients>();
}