// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeAPI.Data.Entities;

public partial class Users
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<MealPlans> MealPlans { get; set; } = new List<MealPlans>();

    public virtual ICollection<Recipes> Recipes { get; set; } = new List<Recipes>();
}